name: Generate Snake Contribution SVG

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:        # Permite executar manualmente pelo GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera os arquivos SVG (tema claro e escuro)
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AlonsoRafael
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica os SVGs no branch `output`
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Atualiza snake SVG [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
